[package]
name = "n-pendulum-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40", features = ["full"] }
plotters = "0.3.7"
base64 = "0.22"
image = "0.25.9"